export enum DroppingDeckActionType {
  INIT_SWAPPED_CARDS = 'INIT_SWAPPED_CARDS',
  DND_DROPPING_DECK_CARD = 'DND_DROPPING_DECK_CARD',
  DND_TMP_DECK_CARD = 'DND_TMP_DECK_CARD',

  DND_TMP_DECK_CARD_CAN_NOT_PUT = 'DND_TMP_DECK_CARD_CAN_NOT_PUT',
}
