export enum BelowCardDroppableArea {
  DROPPABLE1 = 'DROPPABLE1',
  DROPPABLE2 = 'DROPPABLE2',
  DROPPABLE3 = 'DROPPABLE3',
  DROPPABLE4 = 'DROPPABLE4',
  DROPPABLE5 = 'DROPPABLE5',
  DROPPABLE6 = 'DROPPABLE6',
  DROPPABLE7 = 'DROPPABLE7',
  DROPPABLE8 = 'DROPPABLE8',
}

export enum TopLeftTempDekArea {
  TEMP_DECK_1 = 'TEMP_DECK_1',
  TEMP_DECK_2 = 'TEMP_DECK_2',
  TEMP_DECK_3 = 'TEMP_DECK_3',
  TEMP_DECK_4 = 'TEMP_DECK_4',
}

//  黑桃 squade
//  紅心 heart
//  方塊 diamond
//  梅花 club

export enum TopRightFinishDeckDeck {
  FINISH_SQUADE = 'FINISH_SQUADE',
  FINISH_HEART = 'FINISH_HEART',
  FINISH_DIAMOND = 'FINISH_DIAMOND',
  FINISH_CLUB = 'FINISH_CLUB',
}
